# This is a basic workflow to help you get started with Actions

name: AutoMerge

on:
  workflow_dispatch:
  pull_request:
    paths:
      - "folder-allowed/**"
    branches: [ main ]
    types:
      - labeled
  check_suite:
    types:
      - completed
  status: {}
  
jobs:
  weekday:
    runs-on: ubuntu-latest
    outputs:
      day-of-week: ${{steps.day-of-week.outputs.dayOfWeek}}
    steps:
      - name: Getday of week
        id: day-of-week
        run: |
          echo "::set-output name=dayOfWeek::$(date +'%u')"
          echo $(date +'%u') [1 is Monday]
        
  changes:
    runs-on: ubuntu-latest
    outputs:
      taxone-core: ${{ steps.filter.outputs.taxone-core }}
    steps:
      - uses: dorny/paths-filter@v2
        id: filter
        with: 
          filters: |
            taxone-core:
              - 'folder-denied/**'
              - '*.md'
   
  merge:
    needs: [weekday,changes]
    if: ${{ needs.changes.outputs.taxone-core == 'false' && needs.weekday.outputs.day-of-week != 4 }}
    runs-on: ubuntu-latest
    steps:
      - name: create comment
        uses: peter-evans/create-or-update-comment@v1
        with:
          issue-number: ${{ github.event.pull_request.number }}
          body: "Merge feito pelo automerge"
      - name: automerge
        uses: "pascalgn/automerge-action@v0.14.3"
        env:
          GITHUB_TOKEN: "${{ secrets.TOKEN_GITHUB }}"
          MERGE_LABELS: "automerge,!work in progress"
          MERGE_METHOD: "squash"          
          MERGE_RETRIES: "10"
          MERGE_RETRY_SLEEP: "60000"
          MERGE_REQUIRED_APPROVALS: 0
