# This is a basic workflow to help you get started with Actions

name: AutoMerge

on:
  workflow_dispatch:
  pull_request:
    paths:
      - "folder-allowed/**"
    branches: [ main ]
    types:
      - labeled
  check_suite:
    types:
      - completed
  
jobs:
  changes:
    runs-on: ubuntu-latest
    outputs:
      taxone-core: ${{ steps.filter.outputs.taxone-core }}
    steps:
      - uses: dorny/paths-filter@v2
        id: filter
        with: 
          filters: |
            taxone-core:
              - 'folder-denied/**'
  merge:
    needs: changes
    if: ${{ needs.changes.outputs.taxone-core == 'false' }}
    runs-on: ubuntu-latest
    steps:
      - name: create comment
        uses: peter-evans/create-or-update-comment@v1
        with:
          issue-number: ${{ github.event.pull_request.number }}
          body: "Merge feito pelo automerge"
      - name: automerge
        uses: "pascalgn/automerge-action@v0.14.3"
        env:
          GITHUB_TOKEN: "${{ secrets.TOKEN_GITHUB }}"
