# This is a basic workflow to help you get started with Actions

name: AutoMerge

on:
  workflow_dispatch:
  pull_request:
    branches: [ main ]
    types:
      - labeled
  check_suite:
    types:
      - completed
  
jobs:
  merge:
    runs-on: ubuntu-latest
    steps:
      - name: automerge
        uses: "pascalgn/automerge-action@v0.14.3"
        env:
          GITHUB_TOKEN: "${{ secrets.TOKEN_GITHUB }}"
