# This is a basic workflow to help you get started with Actions

name: AutoMerge

on:
  workflow_dispatch:
  pull_request:
    branches: [ main ]    
  
jobs:
  merge:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/github-script@v4
        with:
          script: console.log(context)
