name: Week Day

on: 
  workflow_dispatch:

jobs:
  weekday-job:
    runs-on: ubuntu-latest
    outputs:
      weekday: ${{steps.weekday.outputs.dayOfWeek}}
    steps:
      - name: Get day of week
        id: weekday
        run: echo "::set-output name=dayOfWeek::$(date +'%u')"
  test:
    needs: weekday-job
    runs-on: ubuntu-latest
    steps:
      - name: test weekday
        run: |
          echo "Day of Week" + ${{needs.weekday-job.outputs.weekday}}
          echo "If (string): " + ${{needs.weekday-job.outputs.weekday != '4'}}
          echo "If (number): " + ${{needs.weekday-job.outputs.weekday != 4}}
