name: Week Day

on: 
  workflow_dispatch:

jobs:
  weekday:
    runs-on: ubuntu-latest
    outputs:
      day-of-week: ${{steps.weekday.outputs.dayOfWeek}}
    steps:
      - name: Get day of week
        id: day-of-week
        run: echo "::set-output name=dayOfWeek::$(date +'%u')"
  test:
    needs: weekday
    runs-on: ubuntu-latest
    steps:
      - name: test weekday
        run: |
          echo "Day of Week" + ${{needs.weekday.outputs.day-of-week}}
          echo "If (string): " + ${{needs.weekday.outputs.day-of-week != '4'}}
          echo "If (number): " + ${{needs.weekday.outputs.day-of-week != 4}}
