name: test date

on: workflow_dispatch

jobs:
  date:
    runs-on: ubuntu-latest
    output:
      weekday: ${{steps.dt.outuputs.date}}
    steps:
      - name: calculate-dates-and-times
      - uses: lee-dohm/calculate-dates-and-times@v1.0.2
        id: dt
        with:
          format: ddd
